### ISSUE TITLE
4.27 error

### ISSUE THREAD

**Issue by Dark4331** [KellanM/OpenAI-Api-Unreal#14]
i downloaded the  4.27 from drive but when i open the project this happen "the 'OpenAIAPI' plugin was designed for build 4.26 load it any way?"

**Comment by Diamondkneeplate** [comment]
you run it anway it still works

**Comment by Dark4331** [comment]
sooooo i modified the .upligin to fix that error but still ask me to rebuild from source manually afterwards (tried everything i know but cant fix it)
