### ISSUE TITLE
Api error or apikey is not set

### ISSUE THREAD

**Issue by StephaneMichel** [KellanM/OpenAI-Api-Unreal#15]

**Comment by StephaneMichel** [comment]
I get the same error whenever I play in mode PIE, I had already create a new key but not worked

**Comment by imaekgames** [comment]
I'm getting "Api error" as well, I've tried creating several API keys and trying them, no luck

**Comment by KellanM** [comment]
Can you please review your output log and post the debug message that includes the exact API error you are encountering?

**Comment by Chris9178** [comment]
Hello, thanks a lot for your work, however I'm getting API errors also.
I'm using UE 5.1.1 and using last version of your plugin :

![image](https://user-images.githubusercontent.com/39601757/223477828-bbad4c9d-0363-424c-a850-9f2c704d72c3.png)
![image](https://user-images.githubusercontent.com/39601757/223477911-38b90941-66d5-4f7d-8ad1-67cbd3d00225.png)
![image](https://user-images.githubusercontent.com/39601757/223477993-4ba275d1-1cf9-47c9-84ff-7d4538e1311b.png)

Thanks a lot for help!

**Comment by paulvanvulpen** [comment]
As Cramirez0318 says, your output log will tell you the following:
```
LogTemp: Warning: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

After you connected a credit card to your billing information at the official open AI website the error disappears and the example works.
