### ISSUE TITLE
New Chat Completion

### ISSUE THREAD

**Issue by cirwin518** [KellanM/OpenAI-Api-Unreal#16]
The GPT-3.5-Turbo chat endpoint is live and requires a new completion method.

https://platform.openai.com/docs/guides/chat

**Comment by dicitur** [comment]
Hi! I was wondering too how to implement this into the plugin. I tried modifying the source files to add GPT 3.5-Turbo in the engines list but it doesn't show up in the game editor.

**Comment by KOFli** [comment]
Turbo has different API requests than the other models. Turbo uses https://api.openai.com/v1/chat/completions,OpenAI-Api-Unreal uses "https://api.openai.com/v1/ engines/modelname/completions", in order to support Turbo must upgrade the code.

**Comment by dicitur** [comment]
I see, interesting. Thanks for the answer. Guess it is more complex than just adding a new model line then.

**Comment by KellanM** [comment]
planning in adding support for it this weekend. Whisper is also on my list.

**Comment by dicitur** [comment]
Awesome. Great plugin by the way, thanks a lot.

**Comment by KellanM** [comment]
> > planning in adding support for it this weekend. Whisper is also on my list.
> 
> How's the upgrade coming along? I note that the chat style of completion has a different package to send, so no simple task. Also of note is that GPT4 uses the chat completion format :)

Sorry about the wait - it's been a hectic month but the update is finally here! The plugin now supports ChatGPT models and GPT-4.
