### ISSUE TITLE
New feature of the API

### ISSUE THREAD

**Issue by OrangesFlower** [KellanM/OpenAI-Api-Unreal#18]
Hi! Thanks for developing this great plugin!
There are some useful features in GPT-3.5-Turbo, like chat conversation. Will these methods be added to this plugin? Thank you in advance for the answer!

**Comment by KellanM** [comment]
Yes! Don't have a time estimate for when it will be ready, but I'm already working on it 😄

**Comment by FurrySparkle** [comment]
Is it not just editing the apimethod swtch/case to include the endpoint?

**Comment by FR33K1LL** [comment]
Hey Kellan, hope you're well. How's the update coming along?

**Comment by KellanM** [comment]
Hey Guys! apologies for the wait but the day is finally here. Just added support for gpt-3.5-turbo, gpt-4, and gpt-4-32k
