### ISSUE TITLE
Packaging Error in 4.27

### ISSUE THREAD

**Issue by ManuDass** [KellanM/OpenAI-Api-Unreal#25]
UATHelper: Packaging (Windows (64-bit)):   ERROR: Missing precompiled manifest for 'OpenAIAPI'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in OpenAIAPI.build.cs to override.
UATHelper: Packaging (Windows (64-bit)): Took 0.9622388s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\dougl\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+(x86)+UE_4.27\UBT-HoloGPT-Win64-Development.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=6 (6)
PackagingResults: Error: Missing precompiled manifest for 'OpenAIAPI'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in OpenAIAPI.build.cs to override.
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error

I am currently concluding a project where I implemented chat GPT into a metahuman with lip-syncing that is displayed on my looking glass portrait, however I keep reaching this error when packaging.  Is there a resolution for this that has already been found, did I install the prerequisites wrong?  Some help would be much appreciated.  Thank you!

**Comment by ForeignSone** [comment]
I have the same problem in UE5.0

**Comment by idSynth** [comment]
Is there any solution to this? I need it working in a packaged project and it is supposed to be the main feature of it

**Comment by idSynth** [comment]
I found the solution, simply create "Plugins" folder in your project folder and copy the plugin there, in my case I had to also delete it from the engine directory.
