### ISSUE TITLE
Looks like the creator abonded the project

### ISSUE THREAD

**Issue by chrislvl** [KellanM/OpenAI-Api-Unreal#26]
Would anybody be interested to fork and work on the new methods from ChatGPT with me?

**Comment by dicitur** [comment]
I am no programmer myself, but I really like this plugin and I need to use the GPT 3.5 features in my project. I would be happy to help or even pay someone for the time and work needed to update the plugin if anyone is interested.

**Comment by chrislvl** [comment]
We have enough money thanks, but you are more than welcome to be part of it :)

**Comment by FurrySparkle** [comment]
Dope, I'll follow your fork and see what I can do. Got a nice python call, but can't seem to get it to run in UE. So do actually need to get this working

**Comment by KellanM** [comment]
Just added support for ChatGPT and GPT-4. Still need to update the ReadMe and package the plugin. But if you want to try it right now, download the source code and change the EngineVersion in the .uplugin to your target version. Here's an example implementation:
![image](https://user-images.githubusercontent.com/20115001/229410248-8801310f-745b-470f-b788-07c0bb2f98ae.png)
