### ISSUE TITLE
open AICall completion node is not working

### ISSUE THREAD

**Issue by cruzjunior** [KellanM/OpenAI-Api-Unreal#28]
So I created the open AICall completion node put in as a prompt something very simple which is "what is your name" . After the node I'm using a branch node that takes in the success pin from open AICall completion node and I print out the error message from the open AICall completion node if it is not successful. If it is successful then it continues on to print out the completion.  

But here is where the problem lies:
The output for this is weird. First the branch node fails and outputs Prompt is empty as an error, but then somehow the same branch node succeeds without me even calling it, and it prints out something completely unrelated to the prompt that I gave. 

This issue is with the unreal 5.1.1 version of the plugin and I downloaded it today (April 03, 2023) from the google drive. I was using an older version of the plugin before and it was working fine.

Edit: I am using the Finished output on the open AICall completion node to connect to the branch node

**Comment by KellanM** [comment]
Interesting. Do you mind if we hop in a quick zoom call so I can see your workflow and better understand your problem? https://us05web.zoom.us/j/4206027965?pwd=dlZib1JCdjJSZERWZzUxS3Zvb0NPUT09

**Comment by KellanM** [comment]
Pushed a fix and cruzjunior confirmed it solves his issue.
