### ISSUE TITLE
Stream Function and whisper

### ISSUE THREAD

**Issue by charlo06** [KellanM/OpenAI-Api-Unreal#29]
Hey, first of all just want to say this is an awesome plugin. I've implemented the plugin and works well. Well done on gpt4 and 3.5. Just wanted to ask if you ever plan to support the stream function in the api in the future?
And what about whisper ?
I'm already trying to implement it on my side but i'm having trouble with it. If I ever succeed, i'll make an update here.
Thank you anyway for this awesome plugin

**Comment by KellanM** [comment]
Thank you for the kind words! I’m currently working on adding support for whisper. If you want to take a crack at adding support for streaming I’d be incredibly grateful.

**Comment by KellanM** [comment]
Just added support for Whisper! - I'll close this issue once I upload the new plugin binaries to the project's google drive.

**Comment by charlo06** [comment]
Thanks man can't wait to see how you did it and trying it. Well done!
