### ISSUE TITLE
Error: Json Value of type 'Null' used as a 'Number'

### ISSUE THREAD

**Issue by Sissidark** [KellanM/OpenAI-Api-Unreal#31]
LogJson: Warning: Field index was not found.
LogJson: Error: Json Value of type 'Null' used as a 'Number'.

![image](https://user-images.githubusercontent.com/92515662/232261684-8f81597d-efe9-4eaf-8c59-8fd698d285de.png)
![image](https://user-images.githubusercontent.com/92515662/232261691-ad8fe1b6-221e-471b-8381-be4ceb430f25.png)
![image](https://user-images.githubusercontent.com/92515662/232261694-3796e2f3-6d5b-40c8-9dc8-6f33d3c3bdd1.png)

So what went wrong?
At the same time, if I want to set it as an npc in the game, I want to know how I can customize the content of the role to give him a background setting.

**Comment by KellanM** [comment]
You're close! Connect the execution pin labeled "Finished" from the OpenAICallChat node to the conditional branch node.

**Comment by KellanM** [comment]
to give your NPC background information, manually add one element to your ChatLog array of type "system" and set the message to whatever you want the NPC to do. (i.e. you are a friendly NPC tasked with helping the player learn about x).

**Comment by Sissidark** [comment]
> 要提供您的 NPC 背景信息，请手动将一个类型为“系统”的 ChatLog 数组添加一个元素，并将消息设置为您希望 NPC 执行的任何操作（即您是一个友好的 NPC，负责帮助玩家了解 x）。

I tried to add it manually, but the AI ​​answer seems to be the default setting? Where did I go wrong?

![image](https://user-images.githubusercontent.com/92515662/232263022-0f263427-830e-4dee-b6b3-6ad2de07d5fa.png)

![image](https://user-images.githubusercontent.com/92515662/232262988-f704efee-3176-4f44-b00e-9eb47a2c1126.png)
