### ISSUE TITLE
API Error 

### ISSUE THREAD

**Issue by KevinRyborz** [KellanM/OpenAI-Api-Unreal#35]
Everytime I try to use the CallAI I get an API Error Message, no matter which of the Engines I'm using.

**Comment by KellanM** [comment]
What version of the plugin are you using? Have you set up billing on OpenAI's website?

**Comment by korben1029** [comment]
I got same question, I check my billing, It's free $5.00 for me

**Comment by KevinRyborz** [comment]
> 

I'm currently using version 1.0. But I don't have a billing plan set up. I just blindly followed a tutorial using your plugin and I didn't even think of that. Thanks for the reply!

**Comment by jinskanna** [comment]
I got the same issues and I already pay for the plus account

**Comment by jinskanna** [comment]
First time to report issues I forget to make it clear GPT3 was working but gpt 4 /3.5 turbo failed and I got the error message was [API ERROR] and I got plus account.

**Comment by KellanM** [comment]
@jinskanna having a ChatGPT plus account does not give you access to gpt-4 via the API. You'll need to join the waitlist here: https://openai.com/waitlist/gpt-4-api
