### ISSUE TITLE
Cant Compile plugin with 4.27

### ISSUE THREAD

**Issue by dgod333** [KellanM/OpenAI-Api-Unreal#36]
Trying to compile the binaries of the 4.27 plugin with visual studio, getting a bunch of linker problems such as:

Error		Unrecognized type 'EOAEngineType' - type must be a UCLASS, USTRUCT or UENUM	OBT	OpenAICallGPT.h	36	

probably has to do with the redirs from DefaultOpenAIAPI.ini not working correctly.
The prebuilt 4.27 plugin doesnt not have the whisper functions exposed to BP's. 
(Although, the plugin should preferably be able to compile from source)

Thanks for the plugin btw, only one out there that tries to combine all the OpenAI API's in one.

**Comment by KellanM** [comment]
Great intuition! I forgot to update the .ini in my latest commit. Please let me know if it works now :)
