### ISSUE TITLE
Missing Function and node

### ISSUE THREAD

**Issue by krabakov96** [KellanM/OpenAI-Api-Unreal#37]
Hi there ! I was following the tutorial by MetaHumanSDK for integrating Chat GPT to a metahuman. 
For some reason I'm missing the "Open AICall GPT3" function and nodes. I tried reinstalling the plugin, created new project (5.1.1).. still missing them. Everything shows up as it should except these functions and nodes. Can you assist with that please?

Also what I'm trying to do is not text to speech as the tutorial shows, but whisper/audio to speech. Basically talking to the metahuman and he talking back to me. Possible to get any help on that too ? I will strongly appreciate it. 
I'm just playing around with these new technologies.
Thanks.

**Comment by krabakov96** [comment]
![image](https://user-images.githubusercontent.com/131360354/233361225-8cfe19e1-64d0-427d-a8de-a80fe32411f0.png)

**Comment by amanchauhan2432** [comment]
You can try 2nd node which is "Open AICall Completions". It will work.

**Comment by krabakov96** [comment]
![image](https://user-images.githubusercontent.com/131360354/233395090-db9f36c0-728e-49f6-b8b9-61e934500c13.png)

Yes, but then I need "Make GPT3Settings" Which is also missing... I have the ones I'm showing on the image, but they are not the same as in the tutorial

**Comment by KellanM** [comment]
@krabakov96 MetahumanSDK was using an old version of the plugin when they created their tutorial. The `OpenAICallGPT3` nodes have since been renamed to `OpenAICallCompletions`. The node you’re looking for is `MakeCompletionsSettings`.

**Comment by shivamnyr** [comment]
> @krabakov96 MetahumanSDK was using an old version of the plugin when they created their tutorial. The `OpenAICallGPT3` nodes have since been renamed to `OpenAICallCompletions`. The node you’re looking for is `MakeCompletionsSettings`.

Unable to find `MakeCompletionsSettings`. Please guide.

**Comment by krabakov96** [comment]
![image](https://user-images.githubusercontent.com/131360354/233604577-70f76241-2763-45ff-81e7-8044fe3e04af.png)
Hi, again! I think I properly followed and managed to replace the nodes, but now it is not working at all. When I type something, the AI is not responding at all for some reason. Am I missing something?

**Comment by krabakov96** [comment]
I did set api key. There is no error message, it compiles fine. When I type something, I see in the left corner "generating response", but then nothing happens. Still trying to figure out why it is not working.

**Comment by krabakov96** [comment]
![image](https://user-images.githubusercontent.com/131360354/233698148-bd39cb28-d16a-4e8a-9bee-67901900ff56.png)
So here is what I figured out, that if it's just like that, the AI WORKS, doesn't reply to all questions properly, but still works. And then when I add the new code/nodes that I showed in the image above, it stops working completely. So something in the nodes above is wrong.

**Comment by krabakov96** [comment]
> 

So I did print it when the branch fails and it says "API Error". But I have an API key already. I also generated a new one multiple times and It keeps showing that message.

**Comment by KellanM** [comment]
Can you please show me what appears in your output log when you get the API Error?

**Comment by krabakov96** [comment]
LogTemp: Warning: {
    "error": {
        "message": "Incorrect API key provided: f16f8226************************9127. You can find your API key at https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}

**Comment by krabakov96** [comment]
LogTemp: Warning: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

And this is when I try to generate a new key on the open AI website

**Comment by KellanM** [comment]
@krabakov96 this is expected behavior. You can increase your current quota here: https://platform.openai.com/account/billing/limits
