### ISSUE TITLE
Package project not opening

### ISSUE THREAD

**Issue by amanchauhan2432** [KellanM/OpenAI-Api-Unreal#38]
I package the project and it packaged successfully but when I try to open the .exe file then this error is coming. Do I need to include plugin file during package or anything else. Please any solution

![Package](https://user-images.githubusercontent.com/43270152/233385861-bdf18c28-ed29-4c54-9c5e-55bb2e642937.png)

**Comment by amanchauhan2432** [comment]
@KellanM Please help me with that

**Comment by KellanM** [comment]
I was able to repro this locally. Currently investigating. I'll let you know once I have a solution.

**Comment by vcen** [comment]
I had the same problem.

Assertion failed: CastResult [File:D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Public\UObject\Field.h] [Line: 962] 
CastFieldChecked failed with 0x0000015a98a46300

**Comment by amanchauhan2432** [comment]
I just converted my blueprint project to cpp and it's working

**Comment by amanchauhan2432** [comment]
I just converted my blueprint project to cpp and it's working
