### ISSUE TITLE
When I restart the engine, the nodes show as missing function.

### ISSUE THREAD

**Issue by gypsy264** [KellanM/OpenAI-Api-Unreal#41]
![Screenshot 2023-05-05 122843](https://user-images.githubusercontent.com/70182469/236539216-8ebcf7e7-7797-4093-8956-cb773dc52bab.png)

**Comment by KellanM** [comment]
Very strange. Can you try to reproduce this issue in a new unreal engine project?

**Comment by KellanM** [comment]
Can't reproduce bug
