### ISSUE TITLE
text-davinci-001

### ISSUE THREAD

**Issue by ThrillDaWill** [KellanM/OpenAI-Api-Unreal#5]
Hello! Is it possible to get the new text davinci for unreal? I know it just came out by its seems quite good compared to the current davinci's. Right now im getting all these strange results from my openai in unreal. From printing hundreds of lines of the same thing to not even having context of the conversation and talking about random things.

**Comment by KellanM** [comment]
Hey ThrillDaWill! As of a few hours ago, the plugin supports the new models: text-davinci-001, text-curie-001, text-babbage-001, and text-ada-001. Right now, you can try out the new models in 4.26 by downloading it from my google drive [here](https://drive.google.com/file/d/1Sxa5bmVKVv-XXWe2sJnhJvhnpVCZHH8y/view?usp=sharing):  I'll be building the plugin for other engine versions later this week. :)

**Comment by ThrillDaWill** [comment]
Amazing thank you so much!
