### ISSUE TITLE
Missing gpt3 widget on Mac M1

### ISSUE THREAD

**Issue by Diegozzz72** [KellanM/OpenAI-Api-Unreal#54]
Hi, im new on UE and i try to make a metahuman reply with metahumansdk and Openai, on Mac M1, i installed the plugin in the project plugin folder, as a tutorial from Metahumansdk, they also send me the map, but even if the plugin is loaded, i don't have the option to create the gp3 widget, any help? thank you!

**Comment by KellanM** [comment]
The node has been renamed to OpenAICallCompletions
