### ISSUE TITLE
 I can't find 'Open AICall GPT3' option？Why?

### ISSUE THREAD

**Issue by ffner** [KellanM/OpenAI-Api-Unreal#58]
I'm using UE5.1 and have also downloaded OpenAIAPI5.1.1. However, in the Blueprint editor, I can't find 'Open AICall GPT3' option, only 'Open AICall Chat.' What could be the issue?

**Comment by CocoKele1** [comment]
Yes, I also meet this problem, How did you fix it?

**Comment by ffner** [comment]
Afterwards, I found an industry expert online and spent 200RMB to purchase the OpenAI version plugin from him.
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qiuxin ***@***.***&gt;; 
发送时间: 2023年9月2日(星期六) 下午2:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KellanM/OpenAI-Api-Unreal]  I can&#39;t find &#39;Open AICall GPT3&#39; option？Why? (Issue #58)





 
Yes, I also meet this problem, How did you fix it?

**Comment by KellanM** [comment]
the node has been renamed to OpenAICallCompletions
