### ISSUE TITLE
Getting very bad results compared to what I should be.

### ISSUE THREAD

**Issue by MyAccount420** [KellanM/OpenAI-Api-Unreal#6]
I love the plugin, very easy to use. But the results I get with it are no where near as good as what I get using the GPT playground  or even python API requests with the EXACT same settings. I think this could just be that its not using the latest text-davinci-002.
How could I go about using text-davinci-002 with the plugin?
Thanks

**Comment by KellanM** [comment]
Added support for text-davinci-002.
