### ISSUE TITLE
According to the figure of gpt-3.5, what's wrong with the report?

### ISSUE THREAD

**Issue by yiyang518** [KellanM/OpenAI-Api-Unreal#61]
![image](https://github.com/KellanM/OpenAI-Api-Unreal/assets/49931274/74baf966-e755-487b-affb-995a1ac03890)

**Comment by KellanM** [comment]
you'll need to add an array of messages:
![image](https://github.com/KellanM/OpenAI-Api-Unreal/assets/20115001/6041c316-31d6-414d-bbcb-d792bab7dff2)
