### ISSUE TITLE
Support for UE 5.3

### ISSUE THREAD

**Issue by brybalicious** [KellanM/OpenAI-Api-Unreal#62]
Hello,

Please rebuild for UE5.3.

Thanks!

**Comment by KellanM** [comment]
@brybalicious 
[Here's a version of the plugin that supports 5.3! sorry for the wait](https://drive.google.com/drive/u/2/folders/16FFYDf0U--nxUocQVXCIvSo-Sa0Tnndl)

**Comment by brybalicious** [comment]
Much appreciated!!! Any tips on rebuilding for new engine versions? Seems like it's not as easy as the usual Visual Studio plugin rebuilding process...

**Comment by KellanM** [comment]
Planning on adding it to the marketplace so you won't have to worry about version management. 

In the meantime you can change the Engine Version in the uplugin and rebuild
