### ISSUE TITLE
5.3 Support

### ISSUE THREAD

**Issue by magiclamb** [KellanM/OpenAI-Api-Unreal#63]
Hi would you be able to update this for 5.3 compatibility? It would be awesome to be able to use it in our project soon!

**Comment by KellanM** [comment]
Absolutely! Stay tuned - Adding support for 5.2 and 5.3 this week

**Comment by magiclamb** [comment]
Awesome, thank you! Are you close to the update, we are looking forward to it and will implement it when you do :)

**Comment by magiclamb** [comment]
<img width="1160" alt="image" src="https://github.com/KellanM/OpenAI-Api-Unreal/assets/60589718/6e4992eb-a135-4a1c-98a0-2d7a0e523e23">
Also would you consider putting it on the marketplace like this asset? I feel like a lot more people would find it if it was also there

**Comment by KellanM** [comment]
@magiclamb Good idea! planning on adding it to the marketplace.

[Here's a version of the plugin that supports 5.3. sorry for the wait!:](https://drive.google.com/drive/u/2/folders/16FFYDf0U--nxUocQVXCIvSo-Sa0Tnndl)

**Comment by magiclamb** [comment]
Thanks, looking forward to using it!
Is it this one? ![image](https://github.com/KellanM/OpenAI-Api-Unreal/assets/60589718/9cccbe0b-4f9f-4cd8-8db6-24ea60350115)
