### ISSUE TITLE
Packaging Errors

### ISSUE THREAD

**Issue by nftsimmersive** [KellanM/OpenAI-Api-Unreal#7]
Hi, I left this comment on the YT video also, but packaging the openAI plugin is throwing errors:

This works great in unreal editor in 5, but when I come to package it as a windows build, it is throwing a series of errors. It also may not be relevant, but I note in your readme, you mention using an environment variable for API key, but I couldn't get this to work anyway. I am setting API key as a string variable which works fine for me.

Any idea why unreal would be throwing issues with your openAI BPs? I thought it might be due to variable names/structures, but changing variable names didn't fix the issue.

(I set this up clean in a new UE5 prject also and getting the same errors a second time)

UATHelper: Cooking (Windows): LogInit: Display: LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/BP_OpenAI.BP_OpenAI_C:Finished_4DC25A1040D51A1DC2008AAEC26436FA:completions.completions'. Unknown structure.
UATHelper: Cooking (Windows): LogInit: Display: LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/BP_OpenAI.BP_OpenAI_C:Finished_4DC25A1040D51A1DC2008AAEC26436FA:completionInfo'. Unknown structure.
UATHelper: Cooking (Windows): LogInit: Display: LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/BP_OpenAI.BP_OpenAI_C:ExecuteUbergraph_BP_OpenAI:K2Node_CustomEvent_completions.K2Node_CustomEvent_completions'. Unknown structure.
UATHelper: Cooking (Windows): LogInit: Display: LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/BP_OpenAI.BP_OpenAI_C:ExecuteUbergraph_BP_OpenAI:K2Node_CustomEvent_completionInfo'. Unknown structure.
UATHelper: Cooking (Windows): LogInit: Display: LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/BP_OpenAI.BP_OpenAI_C:ExecuteUbergraph_BP_OpenAI:Temp_struct_Variable'. Unknown structure.
UATHelper: Cooking (Windows): LogInit: Display: LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/BP_OpenAI.BP_OpenAI_C:ExecuteUbergraph_BP_OpenAI:Temp_struct_Variable_1.Temp_struct_Variable_1'. Unknown structure.
UATHelper: Cooking (Windows): LogInit: Display: LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/BP_OpenAI.BP_OpenAI_C:ExecuteUbergraph_BP_OpenAI:CallFunc_Array_Get_Item'. Unknown structure.
UATHelper: Cooking (Windows): LogInit: Display: LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/BP_OpenAI.BP_OpenAI_C:ExecuteUbergraph_BP_OpenAI:K2Node_MakeStruct_GPT3Settings'. Unknown structure.
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: ProxyFactoryClass null in K2Node_AsyncAction /Game/BP_OpenAI.BP_OpenAI:EventGraph.K2Node_AsyncAction_0. Was a class deleted or saved on a non promoted build?
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] BaseAsyncTask: Missing function OpenAICallGPT3 from class Unknown Class for async task  Async Task: Missing Function from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] In use pin  Completions  no longer exists on node  Async Task: Missing Function . Please refresh node or break links to remove pin. from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] In use pin  Error Message  no longer exists on node  Async Task: Missing Function . Please refresh node or break links to remove pin. from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] In use pin  Success  no longer exists on node  Async Task: Missing Function . Please refresh node or break links to remove pin. from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] In use pin  Prompt  no longer exists on node  Async Task: Missing Function . Please refresh node or break links to remove pin. from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] In use pin  Settings  no longer exists on node  Async Task: Missing Function . Please refresh node or break links to remove pin. from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] In use pin  GPT3Settings  no longer exists on node  Make <unknown struct> . Please refresh node or break links to remove pin. from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] In use pin  Max Tokens  no longer exists on node  Make <unknown struct> . Please refresh node or break links to remove pin. from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] In use pin  Temperature  no longer exists on node  Make <unknown struct> . Please refresh node or break links to remove pin. from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] No Struct in  Make <unknown struct> from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] In use pin  <Unnamed>  no longer exists on node  Set Open AIApi Key . Please refresh node or break links to remove pin. from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] Could not find a function named "setOpenAIApiKey" in 'BP_OpenAI'.
UATHelper: Cooking (Windows): Make sure 'BP_OpenAI' has been compiled for  Set Open AIApi Key from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] Could not find a function named "OpenAICallGPT3" in 'BP_OpenAI'.
UATHelper: Cooking (Windows): Make sure 'BP_OpenAI' has been compiled for  Async Task: Missing Function from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI.uasset: [Compiler] Unexpected node type K2Node_AsyncAction encountered at  Async Task: Missing Function from Source: /Game/BP_OpenAI.BP_OpenAI
UATHelper: Cooking (Windows): LogInit: Display: LogBlueprint: Error: [AssetLog] E:\UnreaEngine5\OpenAI5Test\Content\BP_OpenAI

**Comment by nftsimmersive** [comment]
I tried refreshing BP nodes, this doesn't help

**Comment by Spartanus96** [comment]
have you resolve your issue ?

**Comment by nftsimmersive** [comment]
Hi no doesn't work

**Comment by Gobcurry** [comment]
Hello, this problem is also troubling me. Have you solved this problem

**Comment by laoxiongshiye** [comment]
if anyone get know how to fix it，please give me a hand

**Comment by StephaneMichel** [comment]
Hi, same here

**Comment by Shumaro211** [comment]
Same here, all the functions related to the plugin give those errors

**Comment by KellanM** [comment]
I just updated the plugins listed on the drive with a potential fix. Can someone please download and test them out?
